# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ## Source: a Ref/Img/Gold machine
  config.vm.define "source", autostart: false do |source|
    source.vm.box         = "almalinux/9"
    source.vm.box_version = "9.5.20241203"

    source.vm.provider "virtualbox" do |vb|
      vb.cpus   = 2
      vb.memory = "2048"
      vb.check_guest_additions = true
    end

    source.vm.synced_folder "."               , "/vagrant" #, type: "rsync"
    source.vm.synced_folder "../../../scripts", "/scripts" #, type: "rsync"
#   source.vm.synced_folder "../../../iso"    , "/iso"    , type: "rsync"

  end


  ## Update
  config.vm.define "update", autostart: false do |update|
    update.vm.box     = "update/alma-9"
	  update.vm.box_url = "file://package.box"

    update.vm.provider "virtualbox" do |vb|
      vb.cpus   = 2
      vb.memory = "1024"
      vb.check_guest_additions = true
    end

  end

end

