# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ## Source/Ref
  config.vm.define "source", autostart: false do |source|
    source.vm.box = "almalinux/9"
    source.vm.box_version = "9.5.20241203"

    source.vm.provider "virtualbox" do |vb|
      vb.cpus   = 2
      vb.memory = "2048"
      vb.check_guest_additions = true
    end

    source.vm.synced_folder "."               , "/vagrant" #, type: "rsync"
    source.vm.synced_folder "../../../scripts", "/scripts" #, type: "rsync"
#   source.vm.synced_folder "../../../iso"    , "/iso"    , type: "rsync"

#   config.vm.provision "shell", inline: <<-SHELL
#     set -x
#     chmod +x /scripts/*.sh

#     /scripts/timezone.sh
#     /scripts/vagrant.guest-additions.sh
#     /scripts/vagrant.guest-additions.remove.sh -f

#     sudo /scripts/install.epel.sh
#     sudo /scripts/install.pkgs.sh
#     sudo /bin/rm -rf /scripts/*
#     sudo /bin/rm -rf /vagrant/*
#   SHELL
  end


  ## Update
  config.vm.define "output", autostart: false do |output|
    output.vm.box = "update/alma-9"
	  output.vm.box_url = "file://package.box"

    output.vm.provider "virtualbox" do |vb|
      vb.cpus   = 2
      vb.memory = "1024"
      vb.check_guest_additions = true
    end

  end

end

